/**
 * @header {
 *   "module": "workbench-app",
 *   "layer": "component",
 *   "domain": "workbench",
 *   "description": "SCR-001~004를 한 데스크톱 shell에서 연결하는 인터랙티브 목업",
 *   "exports": ["WorkbenchApp"],
 *   "depends": ["mock-workbench-adapter", "shadcn-ui"]
 * }
 */

import { useMemo, useState } from "react";
import { Bot, Boxes, CheckCircle2, ChevronRight, CircleDot, FileCode2, GitCompare, Globe2, ListTree, Plus, RotateCw, Send, Settings2, TerminalSquare } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { MockWorkbenchAdapter } from "./mock-adapter";
import type { Binding, TaskStatus, ToolView, WorkbenchState } from "./types";

const adapter = new MockWorkbenchAdapter();
const streams = [{ id: "product", name: "Product" }, { id: "development", name: "Development" }, { id: "review", name: "Review" }];
const tools: { id: ToolView; label: string }[] = [
  { id: "conversation", label: "Conversation" }, { id: "runs", label: "Runs" }, { id: "terminal", label: "Terminal" }, { id: "browser", label: "Browser" },
  { id: "files", label: "Files" }, { id: "diff", label: "Diff" }, { id: "verification", label: "Verification" }, { id: "result", label: "Result" },
];
const statusLabels: Record<TaskStatus, string> = { todo: "Todo", in_progress: "In progress", review: "Review", done: "Done" };

function BoundaryBadge({ type }: { type: "actual" | "simulated" | "not-connected" }) {
  return <Badge variant={type === "actual" ? "default" : "outline"}>{type === "actual" ? "Actual" : type === "simulated" ? "Simulated" : "Not connected"}</Badge>;
}

function TaskBoard({ state, commit, onClose }: { state: WorkbenchState; commit: (next: WorkbenchState) => void; onClose: () => void }) {
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [error, setError] = useState("");
  const statuses: TaskStatus[] = ["todo", "in_progress", "review", "done"];
  const submit = () => {
    if (!title.trim() || !description.trim()) { setError("제목과 설명을 모두 입력하세요."); return; }
    commit(adapter.createTask(state, title.trim(), description.trim(), state.workstreamId));
    setOpen(false); setTitle(""); setDescription(""); setError("");
  };
  return <div className="absolute inset-0 z-30 flex flex-col gap-4 bg-background p-5" data-testid="task-board">
    <div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">{streams.find((item) => item.id === state.workstreamId)?.name} / Tasks</h2><p className="text-sm text-muted-foreground">카드의 상태 버튼으로 Kanban 열을 이동합니다.</p></div><div className="flex gap-2"><Button onClick={() => setOpen(true)}><Plus data-icon="inline-start" />New Task</Button><Button variant="outline" onClick={onClose}>Workbench로 돌아가기</Button></div></div>
    <div className="grid min-h-0 flex-1 grid-cols-4 gap-3">{statuses.map((status) => <section key={status} className="flex min-w-0 flex-col gap-2 rounded-lg border bg-muted/30 p-3"><div className="flex items-center justify-between text-xs font-semibold uppercase"><span>{statusLabels[status]}</span><Badge variant="secondary">{state.tasks.filter((task) => task.workstreamId === state.workstreamId && task.status === status).length}</Badge></div><ScrollArea className="min-h-0 flex-1"><div className="flex flex-col gap-2 pr-2">{state.tasks.filter((task) => task.workstreamId === state.workstreamId && task.status === status).map((task) => <Card key={task.id}><CardHeader className="p-3"><CardTitle className="text-sm">{task.title}</CardTitle><CardDescription>{task.description}</CardDescription></CardHeader><CardFooter className="flex gap-1 p-3 pt-0"><Button size="sm" variant="ghost" onClick={() => { commit(adapter.select(state, { taskId: task.id, activeToolView: "conversation" })); onClose(); }}>열기</Button><Select value={task.status} onValueChange={(value) => commit(adapter.moveTask(state, task.id, value as TaskStatus))}><SelectTrigger aria-label={`${task.title} 상태`} className="h-9"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{statuses.map((value) => <SelectItem key={value} value={value}>{statusLabels[value]}</SelectItem>)}</SelectGroup></SelectContent></Select></CardFooter></Card>)}</div></ScrollArea></section>)}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>새 Task</DialogTitle><DialogDescription>현재 Stream에 검토용 Task를 만듭니다.</DialogDescription></DialogHeader><div className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="task-title">제목 *</Label><Input id="task-title" value={title} onChange={(event) => setTitle(event.target.value)} aria-invalid={Boolean(error)} /></div><div className="flex flex-col gap-2"><Label htmlFor="task-description">설명 *</Label><Textarea id="task-description" value={description} onChange={(event) => setDescription(event.target.value)} aria-invalid={Boolean(error)} /></div>{error && <Alert variant="destructive"><AlertTitle>입력을 확인하세요</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}</div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>취소</Button><Button onClick={submit}>Task 만들기</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function AgentSheet({ open, onOpenChange, state, commit }: { open: boolean; onOpenChange: (open: boolean) => void; state: WorkbenchState; commit: (next: WorkbenchState) => void }) {
  const [binding, setBinding] = useState<Binding>(state.binding);
  const [saved, setSaved] = useState(false);
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="flex w-[430px] max-w-none flex-col"><SheetHeader><SheetTitle>Agent Catalog</SheetTitle><SheetDescription>Definition과 Runtime Binding을 분리해 검토합니다.</SheetDescription></SheetHeader><div className="flex flex-col gap-3 py-4">{["OPAL PM", "Developer", "Reviewer", "UI Coach"].map((name, index) => <Card key={name}><CardHeader className="flex-row items-center gap-3 p-3"><Avatar><AvatarFallback>{name.slice(0, 2)}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><CardTitle className="text-sm">{name}</CardTitle><CardDescription>{index === 0 ? "project · .opal/AGENT.md" : index === 3 ? "user · offline" : "framework · idle"}</CardDescription></div><BoundaryBadge type={index === 3 ? "not-connected" : "simulated"} /></CardHeader></Card>)}</div><Separator /><div className="flex flex-1 flex-col gap-4 py-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Runtime Binding</h3><BoundaryBadge type="simulated" /></div><div className="flex flex-col gap-2"><Label>Runtime</Label><Select value={binding.runtime} onValueChange={(runtime) => setBinding({ ...binding, runtime, model: runtime === "Claude ACP" ? "claude-sonnet" : "gpt-5.5" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="Codex ACP">Codex ACP</SelectItem><SelectItem value="Claude ACP">Claude ACP</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label>Model</Label><Select value={binding.model} onValueChange={(model) => setBinding({ ...binding, model })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="gpt-5.5">gpt-5.5</SelectItem><SelectItem value="gpt-5.4">gpt-5.4</SelectItem><SelectItem value="claude-sonnet">Claude Sonnet</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex items-center justify-between"><Label htmlFor="permission">도구 권한 자동 허용</Label><Switch id="permission" checked={binding.permission === "allow"} onCheckedChange={(checked) => setBinding({ ...binding, permission: checked ? "allow" : "ask" })} /></div>{saved && <Alert><AlertTitle>설정 저장됨</AlertTitle><AlertDescription>새 Run부터 binding snapshot에 적용됩니다. [Simulated]</AlertDescription></Alert>}</div><SheetFooter><Button variant="outline" onClick={() => setBinding(state.binding)}>되돌리기</Button><Button onClick={() => { commit(adapter.updateBinding(state, binding)); setSaved(true); }}>설정 저장</Button></SheetFooter></SheetContent></Sheet>;
}

function ToolPanel({ state, commit }: { state: WorkbenchState; commit: (next: WorkbenchState) => void }) {
  const task = state.tasks.find((item) => item.id === state.taskId);
  const taskRuns = state.runs.filter((run) => run.taskId === state.taskId);
  const [composer, setComposer] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const send = () => { if (!composer.trim()) return; commit(adapter.sendMention(state, composer.trim())); setComposer(""); };
  if (!task) return <Card><CardHeader><CardTitle>아직 Task가 없습니다</CardTitle><CardDescription>좌측에서 Task를 선택하거나 새 Task를 만드세요.</CardDescription></CardHeader></Card>;
  if (state.activeToolView === "conversation") return <div className="flex h-full flex-col gap-3"><ScrollArea className="min-h-0 flex-1"><div className="flex flex-col gap-3 pr-3">{state.messages.filter((message) => message.taskId === task.id).map((message) => <Card key={message.id}><CardHeader className="flex-row items-center gap-3 p-4"><Avatar><AvatarFallback>{message.author.slice(0, 2)}</AvatarFallback></Avatar><div><CardTitle className="text-sm">{message.author}</CardTitle><CardDescription>{message.body}</CardDescription></div></CardHeader></Card>)}{state.messages.filter((message) => message.taskId === task.id).length === 0 && <Alert><AlertTitle>아직 대화와 Run이 없습니다</AlertTitle><AlertDescription>@OPAL PM 또는 @Developer에게 첫 요청을 보내세요.</AlertDescription></Alert>}</div></ScrollArea><div className="flex gap-2"><Textarea aria-label="Agent 요청" className="min-h-16" value={composer} onChange={(event) => setComposer(event.target.value)} placeholder="@OPAL PM 로그인 오류를 구현해줘" /><Button aria-label="요청 전송" onClick={send}><Send data-icon="inline-start" />Send</Button></div></div>;
  if (state.activeToolView === "runs") return <div className="flex flex-col gap-3">{taskRuns.map((run) => <Card key={run.id}><CardHeader className="p-4"><div className="flex items-center justify-between"><CardTitle className="text-sm">{run.parentRunId && <span className="text-muted-foreground">└ </span>}{run.agent} · {run.id}</CardTitle><Badge variant={run.status === "failed" ? "destructive" : "secondary"}>{run.status}</Badge></div><CardDescription>{run.stage} · {run.progress}% · Runtime snapshot [Simulated]</CardDescription></CardHeader><CardContent className="p-4 pt-0"><Progress value={run.progress} /></CardContent></Card>)}</div>;
  if (state.activeToolView === "terminal") return <Card className="border-dashed"><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><TerminalSquare /> Terminal · env_01</CardTitle><BoundaryBadge type="not-connected" /></div><CardDescription>PTY Runtime은 연결되지 않았으며 아래 출력은 시뮬레이션입니다.</CardDescription></CardHeader><CardContent><pre className="overflow-auto rounded-md bg-muted p-4 text-xs">$ npm test -- --run\n✓ mention delegation flow\n✓ task persistence\n[Simulated output]</pre></CardContent></Card>;
  if (state.activeToolView === "browser") return <div className="grid grid-cols-2 gap-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Globe2 /> Browser actions</CardTitle><CardDescription>탐색 기록 [Simulated]</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{["navigate /login", "fill email", "click submit"].map((step, i) => <Button key={step} variant="outline" className="justify-start">{i + 1}. {step} ✓</Button>)}</CardContent></Card><Card className="border-dashed"><CardHeader><CardTitle>Screenshot preview</CardTitle><CardDescription>CDP / agent-browser Runtime</CardDescription></CardHeader><CardContent><div className="flex aspect-video items-center justify-center rounded-md border bg-muted text-sm text-muted-foreground">Runtime not connected</div></CardContent></Card></div>;
  if (state.activeToolView === "files") return <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileCode2 /> Files · env_01</CardTitle><CardDescription>가상 변경 파일 [Simulated]</CardDescription></CardHeader><CardContent className="flex flex-col gap-2"><code>src/pages/LoginPage.tsx</code><code>src/lib/auth.ts</code><code>src/pages/LoginPage.test.tsx</code></CardContent></Card>;
  if (state.activeToolView === "diff") return <Card><CardHeader><CardTitle className="flex items-center gap-2"><GitCompare /> Git Diff</CardTitle><CardDescription>Git Runtime not connected · patch preview [Simulated]</CardDescription></CardHeader><CardContent><pre className="overflow-auto rounded-md bg-muted p-4 text-xs">- setError(undefined)\n+ setError(&quot;로그인 정보를 확인하세요&quot;)\n+ focusErrorSummary()</pre></CardContent></Card>;
  if (state.activeToolView === "verification") return <div className="flex flex-col gap-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Playwright Verification</h3><BoundaryBadge type="not-connected" /></div><Alert variant={state.verification === "failed" ? "destructive" : "default"}><AlertTitle>{state.verification === "passed" ? "3 checks PASS [Simulated]" : "2 PASS · 1 FAIL [Simulated]"}</AlertTitle><AlertDescription>Browser 탐색과 assertion 결과는 별도 기록입니다.</AlertDescription></Alert><Accordion type="single" collapsible>{["AC-5 mention flow · PASS", "AC-8 evidence mapping · PASS", `AC-11 error state · ${state.verification === "passed" ? "PASS" : "FAIL"}`].map((label, index) => <AccordionItem key={label} value={`check-${index}`}><AccordionTrigger>{label}</AccordionTrigger><AccordionContent>command: playwright test login.spec.ts · evidence: mock://trace/login-{index}.zip</AccordionContent></AccordionItem>)}</Accordion>{state.verification !== "passed" && <Button onClick={() => commit(adapter.rerunVerification(state))}><RotateCw data-icon="inline-start" />실패 검증 재실행</Button>}</div>;
  return <div className="flex flex-col gap-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 /> Result</CardTitle><CardDescription>3 files · {state.verification === "passed" ? "3 pass" : "2 pass · 1 fail"} · Git/Playwright not connected</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><p className="text-sm">로그인 오류 상태와 포커스 흐름을 수정한 목업 결과입니다.</p><div className="flex items-center gap-2"><Switch id="result-confirm" checked={confirmed} onCheckedChange={setConfirmed} /><Label htmlFor="result-confirm">변경·검증·잔여 문제를 확인했습니다</Label></div>{state.approved && <Alert><AlertTitle>Result 승인 완료</AlertTitle><AlertDescription>Task가 Done으로 이동했습니다.</AlertDescription></Alert>}</CardContent><CardFooter><Button disabled={state.verification !== "passed" || !confirmed || state.approved} onClick={() => commit(adapter.approveResult(state))}>결과 승인</Button></CardFooter></Card></div>;
}

export function WorkbenchApp() {
  const [state, setState] = useState(() => adapter.load());
  const [board, setBoard] = useState(false);
  const [agents, setAgents] = useState(false);
  const commit = (next: WorkbenchState) => { setState(next); adapter.save(next); };
  const task = state.tasks.find((item) => item.id === state.taskId);
  const visibleTasks = useMemo(() => state.tasks.filter((item) => item.workstreamId === state.workstreamId), [state.tasks, state.workstreamId]);
  return <main className="relative flex h-screen min-h-[760px] min-w-[1024px] flex-col overflow-hidden bg-background text-foreground">
    <header className="flex h-14 shrink-0 items-center gap-3 border-b px-4"><Boxes /><strong>OPAL</strong><Separator orientation="vertical" className="h-6" /><span className="truncate text-sm text-muted-foreground">{streams.find((item) => item.id === state.workstreamId)?.name} <ChevronRight className="inline size-4" /> {task?.title ?? "Task 선택"}</span><div className="ml-auto flex items-center gap-2"><BoundaryBadge type="actual" /><Badge variant="outline">Interactive mock</Badge><Button variant="outline" size="sm" onClick={() => setBoard(true)}><ListTree data-icon="inline-start" />Board</Button><Button size="sm" onClick={() => setAgents(true)}><Bot data-icon="inline-start" />Agents</Button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-[240px_minmax(520px,1fr)_280px]">
      <aside className="flex min-h-0 flex-col border-r p-3"><p className="mb-2 text-xs font-semibold text-muted-foreground">WORKSTREAMS</p><div className="flex flex-col gap-1">{streams.map((stream) => <Button key={stream.id} variant={stream.id === state.workstreamId ? "secondary" : "ghost"} className="justify-between" onClick={() => commit(adapter.select(state, { workstreamId: stream.id, taskId: state.tasks.find((item) => item.workstreamId === stream.id)?.id }))}><span>{stream.name}</span><Badge variant="outline">{state.tasks.filter((taskItem) => taskItem.workstreamId === stream.id).length}</Badge></Button>)}</div><Separator className="my-3" /><p className="mb-2 text-xs font-semibold text-muted-foreground">TASKS</p><ScrollArea className="min-h-0 flex-1"><div className="flex flex-col gap-1 pr-2">{visibleTasks.map((taskItem) => <Button key={taskItem.id} variant={taskItem.id === state.taskId ? "secondary" : "ghost"} className="h-auto justify-start py-2 text-left" onClick={() => commit(adapter.select(state, { taskId: taskItem.id, activeToolView: "conversation" }))}><CircleDot data-icon="inline-start" /><span className="min-w-0"><span className="block truncate">{taskItem.title}</span><span className="block text-xs text-muted-foreground">{statusLabels[taskItem.status]}</span></span></Button>)}</div></ScrollArea><Button onClick={() => setBoard(true)}><Plus data-icon="inline-start" />New Task</Button></aside>
      <section className="flex min-h-0 min-w-0 flex-col"><div className="flex items-center justify-between border-b px-4 py-3"><div><h1 className="font-semibold">{task?.title ?? "Task를 선택하세요"}</h1><p className="text-xs text-muted-foreground">env_01 · mock worktree · Runtime disconnected</p></div><div className="flex gap-2"><Badge variant="secondary">{task ? statusLabels[task.status] : "Empty"}</Badge><BoundaryBadge type="simulated" /></div></div><Tabs value={state.activeToolView} onValueChange={(value) => commit(adapter.setTool(state, value as ToolView))} className="flex min-h-0 flex-1 flex-col"><TabsList className="mx-3 mt-3 grid h-auto grid-cols-8">{tools.map((tool) => <TabsTrigger key={tool.id} value={tool.id} className="px-2 text-xs">{tool.label}</TabsTrigger>)}</TabsList><div className="min-h-0 flex-1 overflow-auto p-4"><ToolPanel state={state} commit={commit} /></div></Tabs></section>
      <aside className="flex min-h-0 flex-col border-l p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted-foreground">CONTEXT</p><Settings2 className="size-4 text-muted-foreground" /></div><Card className="mt-2"><CardHeader className="p-3"><CardTitle className="text-sm">Entity relations</CardTitle><CardDescription>Project → Task → Run → Environment</CardDescription></CardHeader><CardContent className="flex flex-col gap-1 p-3 pt-0 text-xs"><span>project_opal</span><span>{state.workstreamId}</span><span>{state.taskId ?? "no task"}</span><span>env_01 · shared by Runs</span></CardContent></Card><Separator className="my-3" /><p className="mb-2 text-xs font-semibold text-muted-foreground">ACTIVITY</p><ScrollArea className="min-h-0 flex-1"><div className="flex flex-col gap-2 pr-2">{state.activities.slice().sort((a, b) => a.sequence - b.sequence).map((event) => <button key={event.id} className="rounded-md border p-2 text-left text-xs hover:bg-accent" onClick={() => { const tool: ToolView = event.type === "verification" ? "verification" : event.type === "result" ? "result" : event.type === "file" ? "files" : event.type === "tool" ? "browser" : event.type === "run" || event.type === "delegation" ? "runs" : "conversation"; commit(adapter.setTool(state, tool)); }}><span className="font-medium">{String(event.sequence).padStart(2, "0")} · {event.type}</span><span className="mt-1 block text-muted-foreground">{event.summary}</span></button>)}</div></ScrollArea></aside>
    </div>{board && <TaskBoard state={state} commit={commit} onClose={() => setBoard(false)} />}<AgentSheet open={agents} onOpenChange={setAgents} state={state} commit={commit} />
  </main>;
}
